### ISSUE TITLE
how to fine-tune or retrain matchnet?

### ISSUE THREAD

**Issue by virusme** [hanxf/matchnet#4]
@hanxf, 
Thank you for releasing matchnet evaluation code
I would like to fine-tune or re-train matchnet how do I do that?

Do i train featureNet and metricNet separately. i.e. train featureNet -> computer feature -> train metricNet?

If you can release the training routine then it will be really helpful.

**Comment by hanxf** [comment]
To train/fine-tune jointly, you can connect two FeatureNet to the MetricNet then implement an input layer that feeds batches to the two bottom layers of the FeatureNet. The FeatureNet layers can share parameters by having the same name in the "param" block. You can checkout Caffe's mnist siamese examples.

**Comment by LeonSCZ** [comment]
@hanxf ,i've been on this experiment for a long long time,and my loss was still about 0.69,how can i know the way you train this network?

**Comment by LeonSCZ** [comment]
@hanxf This is my net architecture and my solver file.Do I have any mistakes in my files?Thank you a lot
[mnist_siamese_solver.txt](https://github.com/hanxf/matchnet/files/149380/mnist_siamese_solver.txt)
[mnist_siamese_train_test.txt](https://github.com/hanxf/matchnet/files/149381/mnist_siamese_train_test.txt)

**Comment by 447425299** [comment]
@hanxf Thank for your sharing, i know how to share parameters as  Caffe's mnist siamese examples, but how to connect the two Bottleneck layers to the FC layer. Thank a lot again.

**Comment by 447425299** [comment]
@virusme  Have you done the work? fine-tune the network?

**Comment by virusme** [comment]
@447425299 Apologies for a really late response. I have moved on since I posted this issue (as you can see it is over 3 years old). I cannot remember if I ended up fine tuning the network.
